# Generated by Django 4.2.7 on 2024-03-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prods',
            new_name='prodss',
        ),
    ]
