# Generated by Django 4.2.7 on 2024-03-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prod_type_prodss_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prod_type',
            new_name='ProdType',
        ),
    ]
