# Generated by Django 4.2.7 on 2024-03-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_prod_type_alter_prodss_product_type_delete_prodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodss',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prod_type'),
        ),
    ]
