# Generated by Django 4.2.7 on 2024-03-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_prodss_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodss',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='prod_type',
        ),
    ]
