# Generated by Django 4.2.7 on 2024-03-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_prod_type'),
    ]

    operations = [
    ]
