# Generated by Django 4.2.7 on 2024-03-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240313_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodss',
            name='product_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.prod_type'),
        ),
    ]
