# Generated by Django 4.2.7 on 2024-03-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_prodss_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_type',
            name='category',
        ),
        migrations.AddField(
            model_name='prod_type',
            name='categories',
            field=models.ManyToManyField(to='app.subcatg'),
        ),
    ]
