# Generated by Django 4.2.7 on 2024-03-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_prod_type_category_prod_type_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usef',
        ),
    ]
