from django.urls import path
from .import views

urlpatterns = [
    path('login/',views.loginpage,name='loginurl'),
    path("",views.home, name='homeurl'),
    path("logout/",views.logoutpage,name='logouturl'),
    path('signup/',views.signupPage,name='signupurl'),
    path('register/',views.registerpage,name='registerurl'),
    path('forget/',views.forgot_password, name='forgeturl'),
    path('changepass/',views.changepass,name='changepass'),
    path('verify/',views.password_reset, name='reseturl'),
    path('c/<str:subcategory>/',views.c_view,name='curl'),
    path('uprods/<int:id>/',views.details,name='detailurl'),
    path('address/', views.ProfileView.as_view(), name='address'),
    path('profile/', views.profile, name='profile'),
    path('updateAddress/<int:pk>', views.updateAddress.as_view(), name= 'updateAddress'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('plus_cart/<int:cart_id>/',views.plus_cart,name='plus_cart'),
    path('minus_cart/<int:cart_id>/',views.minus_cart,name='minus_cart'),
    path('remove_cart/<int:cart_id>/',views.remove_cart,name='remove_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('checkout1/',views.checkout1,name='checkout1'),
    path('orders/',views.orders,name='orders'),
    path('aboutus/',views.aboutus,name='aboutusurl'),
    path('services/',views.services,name='servicesurl'),
    path('payment/',views.payment,name='payment'),
    path('buynow/<int:itemid>/',views.buynow,name='buynow'),
    path('addbuynow/<int:itemid>/',views.add_to_buynow,name='add_to_buy'),
    path('plus_buy/<int:item_id>/',views.plus_buy,name='plus_buy'),
    path('minus_buy/<int:item_id>/',views.minus_buy,name='minus_buy'),
    path('remove_buy/<int:item_id>/',views.remove_buy,name='remove_buy'),
    path('buycheckout/',views.buycheckout,name='buycheckout'),
    path('buycheckout1/',views.buycheckout1,name='buycheckout1'),
    path('search/',views.search_view,name='search'),
    path('sort/',views.sort_view,name='sort'),
]